[workspace]
members = [
    "contracts/adventurer",
    "contracts/beasts",
    "contracts/combat",
    "contracts/game",
    "contracts/game_snapshot",
    "contracts/loot",
    "contracts/lords",
    "contracts/market",
    "contracts/obstacles",
]
name = "loot_survivor"
version = "0.1.0"
description = "A fully onchain arcade dungeon crawler built on Starknet in conjunction with Realms.world. Explore the dynamically generated dungeons while you fight for your life against beasts and obstacles in pursuit of a spot on the esteemed leaderboard."
homepage = "https://github.com/provable-games/loot-survivor"

[workspace.dependencies]
starknet = ">=2.5.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }
golden_token = { git = "https://github.com/BibliothecaDAO/golden-token", branch = "next" }
arcade_account = { git = "https://github.com/BibliothecaDAO/arcade-account", branch = "next" }

[workspace.tool.fmt]
sort-module-level-items = true

[scripts]
all = "scarb build && scarb test"
