version: '3.6'

services:
  dna:
    image: quay.io/apibara/starknet:1.5.0
    restart: always
    ports:
      - "7171:7171"
    command:
      - start
      - --rpc
      - http://host.docker.internal:5050
