[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet.workspace = true
loot = { path = "../loot" }
adventurer = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
openzeppelin.workspace = true
golden_token.workspace = true
arcade_account.workspace = true
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
