name: Build Scarb project

on:
  push:
    branches:
      - main
  pull_request:

env:
  SCARB_VERSION: 2.6.5

jobs:
  build:
    name: Build Contracts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract: [
            adventurer,
            game,
            loot,
            market,
            obstacles,
            combat,
            beasts
          ]
    steps:
      - uses: actions/checkout@v3

      - name: Install Scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v ${{ env.SCARB_VERSION }}

      - name: Install Foundry
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | bash && source ~/.bashrc && snfoundryup

      - name: Build and Test ${{ matrix.contract }}
        run: cd contracts/${{ matrix.contract }} && snforge test --max-n-steps 4294967295
